baseurl = "https://ericgar.com/"
languageCode = "en-us"
builddrafts = false
title = "Eric Garrido - ericgar.com"

[pagination]
  pagerSize = 2

[permalinks]
  post = "/:year/:month/:day/:contentbasename/"
  top  = "/:contentbasename/"
