baseurl = "https://ericgar.com/"
languageCode = "en-us"
title = "Eric Garrido - ericgar.com"

[pagination]
  pagerSize = 2

[permalinks]
  post = "/:year/:month/:day/:contentbasename/"
  top  = "/:contentbasename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          # inline = [['\(', '\)']]
[params]
  math = false
